### ISSUE TITLE
Less battery life on macOS

### ISSUE THREAD

**Issue by faust86** [simprecicchiani/ThinkPad-T460s-macOS-OpenCore#111]
I am using standard settings from this repo and it seems that laptop is using only one battery - it lasts max 2,5-3 hours. In Windows everything is OK, both batteries are visible and battery life is 7-8h. I've checked alternative battery settings and they didn't give anything.

**Comment by duszmox** [comment]
Sadly, that's not a bug, both of the batteries are in use, but the battery life is just less than the windows one. This is mainly because macOS is a bit more power hungry than windows. On my device I get 5-6 hours on Windows and 4-5 on macOS. Also macOs won't show the two batteries separately because there isn't any macbooks out there with more than battery, so Apple didn't implament this feature.
