### ISSUE TITLE
How to generate SSDT-CPU

### ISSUE THREAD

**Issue by nijhawank** [simprecicchiani/Thinkpad-T460s-macOS-OpenCore#2]
Hello, 

You state that you can create your SSDT-CPU with the following steps...

1. Use CPUFriendFriend with desired LFM and EPP profiles which generates a modified plist for my Mac model

2. Use the plist from step 1 to generate ssdt_data with ResourceConverter script in CPUFriend. 

3. Then merge the resultant ssdt_data from Step 2 with CPU-PLUG which is renamed to SSDT-CPU

However, I noticed the following...

1. CPUFriendFriend directly generates ssdt_data without going through step 2.

2. When I decompiled your SSDT-CPU, I  see that it has content generated with Piker-Alpha’s ssdtPrGen. Did you mean to merge ssdt_data from CPUFriendFriend (or the ResourceConverter script) with the SSDT generated from Piker-Alpha’s ssdtPrGen? But then I read at many places  that Piker-Alpha’s ssdtPrGen is not needed or obsolete these days. Can you please explain your usage.

Other questions...
1. The template SSDT-PLUG is for only CPU0, what is the right thing to do for other processor cores? 

Thanks in advance.

**Comment by simprecicchiani** [comment]
Hi, as I was saying on Insanelymac's forum, these days I'm trying different stuff to see what does what.  In addition, I'm relatively young to the Hackintosh word; I started only half a year ago, so please, don't assume that what I do is the best way to go. 
However, I'm pleased by the response of the community that my work has generated and I'm happy to receive feedback by all of you.

Now speaking about the issue, first thing first, running CPUFrindFriend' script in my case results only in a plist. I did not inspected the script itself since I'm pretty sure it's well crafted by Corpnewt.

I previously tried plain CPU-PLUG with CPUFriend.kext and CPUFirendDataProvider.kext, the I switched to Piker-Alpha’s SSDT with data from ssdt-data.
Haven't really noticed any differences and don't know how to test the result of this work (let me know if you do, I would be happy to benchmark everything).
All I can say is that I'm using the laptop for about 6 hrs/day and it is very reliable and snappy in any task.

Concerning the last question, in OpenCore, you only want to connect the first thread of the CPU.
Take a look here https://khronokernel.github.io/Getting-Started-With-ACPI/Universal/plug.html
